-- EFDA-ETSwitch initial schema (ported from facility-license-be 025/026)
CREATE SCHEMA IF NOT EXISTS payment;
CREATE TABLE IF NOT EXISTS payment.ethswitch_transaction (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_info_id         integer NOT NULL,
    application_id          integer NOT NULL,
    merch_order_id          character varying(64) NOT NULL,
    order_reference         character varying(64),
    hpp_token               character varying(64),
    bill_payment_request_id character varying(64),
    trans_id                character varying(64),
    trade_status            character varying(20) NOT NULL DEFAULT 'PENDING',
    total_amount            numeric(12,2) NOT NULL,
    trans_currency          character varying(10) NOT NULL DEFAULT 'ETB',
    title                   character varying(128),
    checkout_url            text,
    raw_callback            text,
    initiated_at            timestamp with time zone NOT NULL DEFAULT now(),
    expires_at              timestamp with time zone,
    callback_received_at    timestamp with time zone,
    created_date            timestamp without time zone NOT NULL DEFAULT now(),
    modified_date           timestamp without time zone NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_ethswitch_tx_merch_order_id
    ON payment.ethswitch_transaction (merch_order_id);
CREATE INDEX IF NOT EXISTS idx_ethswitch_tx_payment_info_id
    ON payment.ethswitch_transaction (payment_info_id);
CREATE INDEX IF NOT EXISTS idx_ethswitch_tx_trade_status
    ON payment.ethswitch_transaction (trade_status);
