-- Telebirr H5 C2B payment tables
CREATE TABLE IF NOT EXISTS payment.telebirr_transaction (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_info_id         integer NOT NULL,
    application_id          integer NOT NULL,
    merch_order_id          character varying(64) NOT NULL,
    payment_order_id        character varying(64),
    trans_id                character varying(64),
    trade_status            character varying(20) NOT NULL DEFAULT 'PENDING',
    total_amount            numeric(12,2) NOT NULL,
    trans_currency          character varying(3) NOT NULL DEFAULT 'ETB',
    title                   character varying(128),
    prepay_id               character varying(64),
    checkout_url            text,
    reconciled_at           timestamp with time zone,
    reconcile_attempts      integer NOT NULL DEFAULT 0,
    initiated_at            timestamp with time zone NOT NULL DEFAULT now(),
    callback_received_at    timestamp with time zone,
    created_date            timestamp without time zone NOT NULL DEFAULT now(),
    modified_date           timestamp without time zone NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_telebirr_tx_merch_order_id
    ON payment.telebirr_transaction (merch_order_id);
CREATE INDEX IF NOT EXISTS idx_telebirr_tx_payment_info_id
    ON payment.telebirr_transaction (payment_info_id);
CREATE INDEX IF NOT EXISTS idx_telebirr_tx_application_id
    ON payment.telebirr_transaction (application_id);
CREATE INDEX IF NOT EXISTS idx_telebirr_tx_trade_status
    ON payment.telebirr_transaction (trade_status);

CREATE TABLE IF NOT EXISTS payment.telebirr_api_log (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    direction           character varying(10) NOT NULL,
    api_method          character varying(50) NOT NULL,
    merch_order_id      character varying(64),
    correlation_id      character varying(32),
    request_payload     text,
    response_payload    text,
    http_status_code    integer,
    resp_code           character varying(10),
    resp_desc           character varying(256),
    signature_valid     boolean,
    processing_status   character varying(20) DEFAULT 'RECEIVED',
    processing_error    text,
    duration_ms         integer,
    created_at          timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_telebirr_api_log_merch_order
    ON payment.telebirr_api_log (merch_order_id);
CREATE INDEX IF NOT EXISTS idx_telebirr_api_log_created
    ON payment.telebirr_api_log (created_at);
