-- Canonical payment records and callback audit logs
CREATE TABLE IF NOT EXISTS payment.payment (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_info_id         integer NOT NULL,
    application_id          integer NOT NULL,
    transaction_reference   character varying(64) NOT NULL,
    provider_transaction_id character varying(128),
    amount                  numeric(12,2) NOT NULL,
    currency                character varying(10) NOT NULL DEFAULT 'ETB',
    payment_status          character varying(20) NOT NULL DEFAULT 'PENDING',
    payment_method          character varying(32) NOT NULL,
    provider                character varying(32) NOT NULL,
    callback_payload        text,
    callback_received_at    timestamp with time zone,
    created_at              timestamp with time zone NOT NULL DEFAULT now(),
    updated_at              timestamp with time zone NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_payment_provider_tx_ref
    ON payment.payment (provider, transaction_reference);
CREATE INDEX IF NOT EXISTS idx_payment_payment_info_id
    ON payment.payment (payment_info_id);
CREATE INDEX IF NOT EXISTS idx_payment_status
    ON payment.payment (payment_status);

CREATE TABLE IF NOT EXISTS payment.payment_callback_log (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider                character varying(32) NOT NULL,
    correlation_id          character varying(64),
    transaction_reference   character varying(64),
    request_headers         text,
    request_body            text,
    source_ip               character varying(64),
    processing_result       character varying(32) NOT NULL,
    processing_error        text,
    duration_ms             integer,
    received_at             timestamp with time zone NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_payment_callback_log_provider
    ON payment.payment_callback_log (provider);
CREATE INDEX IF NOT EXISTS idx_payment_callback_log_tx_ref
    ON payment.payment_callback_log (transaction_reference);

-- EthSwitch API audit log (referenced by entity; missing from 001_etswitch.sql)
CREATE TABLE IF NOT EXISTS payment.ethswitch_api_log (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    direction           character varying(10) NOT NULL,
    api_method          character varying(50) NOT NULL,
    merch_order_id      character varying(64),
    correlation_id      character varying(32),
    request_payload     text,
    response_payload    text,
    http_status_code    integer,
    resp_code           character varying(10),
    resp_desc           character varying(256),
    processing_status   character varying(20) NOT NULL DEFAULT 'RECEIVED',
    processing_error    text,
    duration_ms         integer,
    created_at          timestamp with time zone NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_ethswitch_api_log_merch_order_id
    ON payment.ethswitch_api_log (merch_order_id);
